# Generated by Django 3.1.2 on 2023-04-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('image', models.URLField(max_length=255, verbose_name='Картинка')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(verbose_name='Есть в наличии')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
