# Generated by Django 3.1.2 on 2023-04-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default='name', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
