# Generated by Django 3.1.2 on 2023-04-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20230402_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, verbose_name='Модель'), max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
